apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: desafio-devops-alert-config
  namespace: monitoring
spec:
  route:
    groupBy:
    - namespace
    continue: false
    routes:
    - receiver: 'telegram'
      matchers:
      - alertname=~"InfoInhibitor|Watchdog"
      continue: false
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
  # inhibitRules:
  # - sourceMatch: [severity: critical"]
  #   targetMatch: [severity: ~"warning|info"]
  #   equal:
  #   - namespace
  #   - alertname
  # - sourceMatch: [severity=: "warning"]
  #   targetMatch: [severity: "info"]
  #   equal:
  #   - namespace
  #   - alertname
  # - sourceMatch: [alertname: "InfoInhibitor"]
  #   targetMatch: [severity: "info"]
  #   equal:
  #   - namespace
  receivers:
  - name: 'telegram'
    telegramConfigs:
    - botToken: 
        name: desafio-devops-bot-token
        key: token
      chatID: 1001851075210