apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
spec:
  route:
    repeatInterval: 30m
    routes:
    - receiver: 'telegram'
  receivers:
  - name: 'telegram'
    telegramConfigs:
    - bot_token: 
        name: desafio-devops-bot-token
        key: token
      chat_id: 1001851075210