apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: desafio-devops-alert-config
  namespace: monitoring
spec:
  route:
    groupBy:
    - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 30m
    receiver: 'telegram'
  receivers:
  - name: 'telegram'
    telegramConfigs:
    - botToken: 
        name: desafio-devops-bot-token
        key: token
      chatID: 1001851075210