apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: meudeploy
  name: meudeploy
  namespace: segredosdesucesso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meudeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meudeploy
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app
          name: app-secret-vol
        resources: {}
      volumes:
      - name: app-secret-vol
        secret:
          secretName: meusegredo
status: {}
