apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: meu-spread
spec:
  selector:
    matchLabels:
      app: meu-spread
  template:
    metadata:
      labels:
        app: meu-spread
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
