apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: guardaroupa
  name: guardaroupa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guardaroupa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guardaroupa
    spec:
      containers:
      - image: redis
        name: redis
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: guardaroupa
  name: guardaroupa
spec:
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: guardaroupa
  type: ClusterIP
status:
  loadBalancer: {}
