apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: backend
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: meusiteset
  name: meusiteset
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meusiteset
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meusiteset
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: vol-data
        resources: {}
      volumes:
      - name: vol-data
        persistentVolumeClaim:
          claimName: pvc-data        
status: {}

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-io-priority-high
  namespace: backend
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  snap_interval:   "70"
  priority_io:  "high"

# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data
  storageClassName: portworx-io-priority-high

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: backend
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: portworx-io-priority-high
  resources:
    requests:
      storage: 1Gi